### ISSUE TITLE
How to install on laravel 4.2

### ISSUE THREAD

**Issue by SamuelEshetu** [princealikhan/paytm-payment#10]
Can you please help me to install on laravel 4.2

**Comment by princealikhan** [comment]
sure let me know what issue you are facing.

**Comment by SamuelEshetu** [comment]
Hello

I am getting below error.

This I am using https://github.com/trocho/laravel-paytm

E:\Projects\php\shbak\user\protected>composer require trocho/laravel-paytm
Using version ^1.0 for trocho/laravel-paytm
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v4.2.17
    - Conclusion: don't install laravel/framework v4.2.17
    - trocho/laravel-paytm v1.0 requires illuminate/support 5.0.*|5.1.* -> satis
fiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33
, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28,
v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - trocho/laravel-paytm v1.0.1 requires illuminate/support 5.0.*|5.1.* -> sat
isfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.
33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28
, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - trocho/laravel-paytm v1.0.2 requires illuminate/support 5.0.*|5.1.* -> sat
isfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.
33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28
, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - trocho/laravel-paytm v1.0.3 requires illuminate/support 5.0.*|5.1.* -> sat
isfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.
33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28
, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - trocho/laravel-paytm v1.0.4 requires illuminate/support 5.0.*|5.1.* -> sat
isfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.
33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28
, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - trocho/laravel-paytm v1.0.5 requires illuminate/support 5.0.*|5.1.*|5.2.*
-> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28,
 v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v
5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.
2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5
.2.45, v5.2.6, v5.2.7].
    - trocho/laravel-paytm v1.0.6 requires illuminate/support 5.0.*|5.1.*|5.2.*|
5.3.* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5
.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1
.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.2
1, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.
43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.0.22|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.0.25|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.0.26|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.0.28|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.0.33|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.0.4|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.1.1|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.1.13|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.1.16|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.1.2|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.1.20|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.1.22|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.1.25|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.1.28|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.1.30|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.1.31|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.1.41|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.1.6|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.1.8|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.2.0|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.2.19|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.21|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.24|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.25|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.26|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.27|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.28|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.31|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.32|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.37|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.43|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.45|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.6|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.2.7|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.3.0|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.3.16|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.3.23|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.3.4|don't install laravel/framework v4
.2.17
    - Installation request for laravel/framework (locked at v4.2.17, required as
 4.2.*) -> satisfiable by laravel/framework[v4.2.17].
    - Installation request for trocho/laravel-paytm ^1.0 -> satisfiable by troch
o/laravel-paytm[v1.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6].


Installation failed, reverting ./composer.json to its original content.

**Comment by SamuelEshetu** [comment]
I have also run using below command.


E:\Projects\php\shbak\user\protected>composer require princealikhan/paytm-paymen
t
Using version ^1.0 for princealikhan/paytm-payment
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v4.2.17
    - Conclusion: don't install laravel/framework v4.2.17
    - princealikhan/paytm-payment v1.0 requires illuminate/support 5.0.*|5.1.* -
> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28,
v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5
.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - princealikhan/paytm-payment v1.0.1 requires illuminate/support 5.0.*|5.1.*
 -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28
, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25,
v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - princealikhan/paytm-payment v1.0.2 requires illuminate/support 5.0.*|5.1.*
 -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28
, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25,
v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - princealikhan/paytm-payment v1.0.3 requires illuminate/support 5.0.*|5.1.*
 -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28
, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25,
v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - princealikhan/paytm-payment v1.0.4 requires illuminate/support 5.0.*|5.1.*
 -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28
, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25,
v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - princealikhan/paytm-payment v1.0.5 requires illuminate/support 5.0.*|5.1.*
|5.2.* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v
5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.
1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.
21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2
.43, v5.2.45, v5.2.6, v5.2.7].
    - princealikhan/paytm-payment v1.0.6 requires illuminate/support 5.0.*|5.1.*
|5.2.*|5.3.* -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0
.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.2
2, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19,
 v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37
, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.0.22|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.0.25|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.0.26|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.0.28|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.0.33|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.0.4|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.1.1|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.1.13|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.1.16|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.1.2|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.1.20|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.1.22|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.1.25|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.1.28|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.1.30|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.1.31|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.1.41|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.1.6|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.1.8|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.2.0|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.2.19|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.21|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.24|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.25|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.26|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.27|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.28|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.31|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.32|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.37|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.43|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.45|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.2.6|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.2.7|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.3.0|don't install laravel/framework v4
.2.17
    - don't install illuminate/support v5.3.16|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.3.23|don't install laravel/framework v
4.2.17
    - don't install illuminate/support v5.3.4|don't install laravel/framework v4
.2.17
    - Installation request for laravel/framework (locked at v4.2.17, required as
 4.2.*) -> satisfiable by laravel/framework[v4.2.17].
    - Installation request for princealikhan/paytm-payment ^1.0 -> satisfiable b
y princealikhan/paytm-payment[v1.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0
.6].


Installation failed, reverting ./composer.json to its original content.
