### ISSUE TITLE
Composer require fails for laravel 5.2

### ISSUE THREAD

**Issue by manjyot** [princealikhan/paytm-payment#6]
I need to integrate paytm gateway on a laravel 5.2.45 project. Dependency errors come up.

**Comment by princealikhan** [comment]
Can you please share what error you are getting. i will help you to setup

**Comment by princealikhan** [comment]
Hey Manjyot, 
I have created a new release to support laravel 5.2 version 
please use the updated release and let me know if it works.

**Comment by manjyot** [comment]
@princealikhan Thanks. I will check and let you know asap.

**Comment by vijaythecoder** [comment]
This is giving me error when I install with laravel 5.3 `minimum stability problem`, can you help with that please? :)
